# Generated by Django 4.1.4 on 2022-12-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Member'), (2, 'Director'), (3, 'Executive Council'), (4, 'Assistant Director'), (5, 'Sponsor'), (6, 'Patron')], default=1, max_length=20),
        ),
    ]
