# Generated by Django 4.0.8 on 2022-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Member', 'Member'), ('Director', 'Director'), ('Executive Council', 'Executive Council'), ('Assistant Director', 'Assistant Director'), ('Sponsor', 'Sponsor'), ('Patron', 'Patron')], default='Member', max_length=20),
        ),
    ]
