# Generated by Django 4.0.8 on 2022-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=120)),
                ('event_head', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField()),
                ('event_venue', models.CharField(max_length=120)),
                ('dept_id', models.IntegerField()),
                ('num_team_members', models.IntegerField()),
                ('sponsor_id', models.IntegerField()),
                ('sponsor_name', models.CharField(max_length=120)),
                ('budget', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
