# Generated by Django 4.1.4 on 2022-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100, null=True)),
                ('dept_name', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Finance and Legal', 'Finance and Legal'), ('Events', 'Events'), ('Marketing', 'Marketing'), ('Outreach', 'Outreach'), ('Design', 'Design')], max_length=100, null=True)),
                ('dept_id', models.IntegerField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')], max_length=20, null=True)),
                ('email_id', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role_name', models.CharField(choices=[('Member', 'Member'), ('Director', 'Director'), ('Executive Council', 'Executive Council'), ('Assistant Director', 'Assistant Director')], max_length=200)),
                ('role_id', models.IntegerField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04')], null=True)),
            ],
        ),
    ]
