# Generated by Django 4.1.4 on 2022-12-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dept_id',
            field=models.IntegerField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')], null=True),
        ),
    ]
