# Generated by Django 4.1.4 on 2022-12-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_members_dept_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
