# Generated by Django 4.1 on 2022-12-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_members_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dept_id',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_id',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
