# Generated by Django 4.1 on 2022-12-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_member_dept_id_alter_member_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60)], primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('Human Resources', 'Human Resources'), ('Finance and Legal', 'Finance and Legal'), ('Events', 'Events'), ('Marketing', 'Marketing'), ('Outreach', 'Outreach'), ('Design', 'Design')], default='Human Resources', max_length=100)),
                ('num_members', models.IntegerField(blank=True, null=True)),
                ('num_directors', models.IntegerField(blank=True, null=True)),
                ('num_ads', models.IntegerField(blank=True, null=True)),
                ('acc_num', models.IntegerField(blank=True, null=True)),
                ('total_bal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('Member', 'Member'), ('Director', 'Director'), ('Executive Council', 'Executive Council'), ('Assistant Director', 'Assistant Director')], default='Member', max_length=100)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('min_people', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.department'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
    ]
