# Generated by Django 4.1.4 on 2022-12-10 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0007_member_admin_alter_member_dept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.department')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantDirector',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dept_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.department')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
            ],
        ),
    ]
