# Generated by Django 4.1.4 on 2022-12-10 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0008_ec_director_assistantdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('patron_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patron_name', models.CharField(max_length=100, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
