# Generated by Django 4.0.8 on 2022-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_member_id_patron_patron_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='patron_id',
            new_name='member_id',
        ),
    ]
