# Generated by Django 4.0.8 on 2022-12-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_assistantdirector_member_id_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='sponsor',
    #         name='sponsor_id',
    #     ),
    # ]
