# Generated by Django 4.0.8 on 2022-12-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_sponsor_sponsor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_id',
        ),
        migrations.AlterField(
            model_name='assistantdirector',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assistantdirector',
            name='role_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
        migrations.AlterField(
            model_name='director',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='role_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
        migrations.AlterField(
            model_name='ec',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ec',
            name='role_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='member_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
